# Training datasets for different folds
datasets:
    - ml/mt/fold0_mt_training_dataset.root
    - ml/mt/fold1_mt_training_dataset.root

# Base path for all output files
output_path: ml/mt

# Define classes based on tree names in dataset file
classes:
    - ggh
    - qqh
    - ztt
    - zll
    - w
    - ss
    - misc

# Set class weights
class_weights:
    ggh: 213.2
    qqh: 2173.2
    ztt: 1.6
    zll: 19.9
    w: 8.0
    tt: 17.9
    ss: 6.9
    misc: 86.0

# Define global scale factor, which is multiplied to all event weights
global_weight_scale: 1.0

# Set event weight variable
event_weights: training_weight

# Define list of variables to be used for training
variables:
    - m_sv
    - pt_1
    - pt_2
    - eta_2
    - njets
    - nbtag
    - mt_1
    - mt_2
    - ptvis
    - pt_tt
    - m_vis
    - met

# Split of dataset in training and validation (in TMVA called training and testing)
train_test_split: 0.75

# Define preprocessing
preprocessing: standard_scaler

# Set random seed for initialization of parameters and dataset splits
seed: 1234

# Define the model parameter
model:
    name: smhtt_dropout
    batch_size: 1000
    epochs: 10000
    early_stopping: 20
    save_best_only: true
